/**
 * Chat Service implementation for Chat Assistant
 */

import { CascadeRouter } from '@lsi/cascade';
import { SemanticCache } from '@lsi/cascade';
import { RAGPipeline, RAGResult, DocumentChunk } from './rag.js';
import { ChatAssistantConfig } from './config.js';

export interface ChatMessage {
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: number;
}

export interface ChatResponse {
  content: string;
  fromCache: boolean;
  ragUsed: boolean;
  model: string;
  latency: number;
  confidence: number;
}

export class ChatService {
  private router: CascadeRouter;
  private cache: SemanticCache;
  private rag?: RAGPipeline;
  private config: ChatAssistantConfig;
  private conversationHistory: ChatMessage[] = [];

  constructor(
    router: CascadeRouter,
    cache: SemanticCache,
    config: ChatAssistantConfig,
    rag?: RAGPipeline
  ) {
    this.router = router;
    this.cache = cache;
    this.config = config;
    this.rag = rag;
  }

  /**
   * Process a chat message
   */
  async chat(userMessage: string): Promise<ChatResponse> {
    const startTime = Date.now();

    // Add user message to history
    this.conversationHistory.push({
      role: 'user',
      content: userMessage,
      timestamp: Date.now(),
    });

    // Check cache first
    if (this.config.cache_enabled) {
      const cached = await this.checkCache(userMessage);
      if (cached) {
        this.addToHistory('assistant', cached.content);
        return {
          ...cached,
          latency: Date.now() - startTime,
        };
      }
    }

    // Retrieve relevant context if RAG is enabled
    let ragContext = '';
    let ragUsed = false;
    if (this.config.rag_enabled && this.rag) {
      const ragResult = await this.rag.retrieve(userMessage);
      ragContext = ragResult.context;
      ragUsed = ragResult.chunks.length > 0;
    }

    // Build prompt with context and history
    const prompt = this.buildPrompt(userMessage, ragContext);

    // Route and generate response
    const routingDecision = await this.router.route({
      query: prompt,
      context: this.getRecentContext(),
    });

    const response = await this.generateResponse(prompt, routingDecision.model);

    // Add to history
    this.addToHistory('assistant', response);

    // Cache the response
    if (this.config.cache_enabled) {
      await this.cacheResponse(userMessage, response, routingDecision.model);
    }

    // Trim history if needed
    this.trimHistory();

    return {
      content: response,
      fromCache: false,
      ragUsed,
      model: routingDecision.model,
      latency: Date.now() - startTime,
      confidence: routingDecision.confidence,
    };
  }

  /**
   * Build prompt with context and history
   */
  private buildPrompt(userMessage: string, ragContext: string): string {
    let prompt = '';

    // Add RAG context if available
    if (ragContext) {
      prompt += `Relevant Context:\n${ragContext}\n\n`;
    }

    // Add conversation history
    const recentHistory = this.getRecentHistory(this.config.context_window);
    if (recentHistory.length > 0) {
      prompt += 'Conversation History:\n';
      for (const msg of recentHistory) {
        prompt += `${msg.role}: ${msg.content}\n`;
      }
      prompt += '\n';
    }

    // Add current message
    prompt += `User: ${userMessage}\nAssistant:`;

    return prompt;
  }

  /**
   * Generate response using model
   */
  private async generateResponse(prompt: string, model: string): Promise<string> {
    // Placeholder - in real implementation, this would call the model
    // For now, return a mock response
    return `[Response from ${model}]\n\nThis is a placeholder response. In production, this would be generated by ${model} based on the prompt.`;
  }

  /**
   * Check cache for existing response
   */
  private async checkCache(query: string): Promise<ChatResponse | null> {
    // Placeholder - use SemanticCache
    return null;
  }

  /**
   * Cache a response
   */
  private async cacheResponse(query: string, response: string, model: string): Promise<void> {
    // Placeholder - use SemanticCache
  }

  /**
   * Get recent conversation history
   */
  private getRecentHistory(count: number): ChatMessage[] {
    return this.conversationHistory.slice(-count * 2); // *2 for user+assistant pairs
  }

  /**
   * Get recent context for routing
   */
  private getRecentContext(): Record<string, unknown> {
    const recent = this.getRecentHistory(3);
    return {
      recent_messages: recent.map((m) => ({ role: m.role, content: m.content })),
      message_count: this.conversationHistory.length,
    };
  }

  /**
   * Add message to history
   */
  private addToHistory(role: 'user' | 'assistant', content: string): void {
    this.conversationHistory.push({
      role,
      content,
      timestamp: Date.now(),
    });
  }

  /**
   * Trim history to prevent memory bloat
   */
  private trimHistory(): void {
    const maxHistory = this.config.context_window * 2 * 2; // 2x buffer
    if (this.conversationHistory.length > maxHistory) {
      this.conversationHistory = this.conversationHistory.slice(-maxHistory);
    }
  }

  /**
   * Clear conversation history
   */
  clearHistory(): void {
    this.conversationHistory = [];
  }

  /**
   * Get conversation history
   */
  getHistory(): ChatMessage[] {
    return [...this.conversationHistory];
  }

  /**
   * Stream chat response
   */
  async *chatStream(userMessage: string): AsyncGenerator<string, void, unknown> {
    // For streaming, we'd yield chunks as they arrive
    const response = await this.chat(userMessage);
    const words = response.content.split(/\s+/);

    for (const word of words) {
      yield word + ' ';
      // Simulate streaming delay
      await new Promise((resolve) => setTimeout(resolve, 50));
    }
  }
}
